version: '3.9'

services:
  db:
    image: postgres:13.16
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: pgadmin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres-chat:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres-chat:
