version: '3.9'

services:
  db:
    image: postgres:13.16
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_DB: tests
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - .:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres: